In [130]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np


In [ ]:
np.__version__

'1.21.6'

In [7]:
arr = np.array([1,2,3,4])
arr.shape

(4,)

In [8]:
arr.ndim

1

In [15]:
arr_2d = np.array([[1,2,3,4,5,6,8]])

In [16]:
arr_2d.shape

(1, 7)

In [17]:
arr_2d.ndim

2

In [19]:
b = np.arange(12)

In [21]:
b #creates a array upto the given number

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Array Reshaping

In [22]:
b = np.arange(12).reshape(3,4)

In [23]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
b.ndim

2

# Indexing in 2-d arrays

1st index indicates the row and the second indicates the column.

In [25]:
b[0][3]

3

# Array with random values within the given range.
The first two arguements specifies the range and the third argument is for the size of the array.

if we set the seed value same for two arrays then the values in the array will be same

In [46]:
np.random.seed(0)

In [47]:
arr_random = np.random.randint(0,10,(3,3))

In [48]:
arr_random

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [49]:
np.random.seed(0)

In [50]:
arr_random = np.random.randint(0,10,(3,3))

In [51]:
arr_random

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

# Create a integer array of 2*10 filled with random values

In [56]:
random = np.random.randint(500,600,(2,10))

In [57]:
random

array([[587, 570, 588, 588, 512, 558, 565, 539, 587, 546],
       [588, 581, 537, 525, 577, 572, 509, 520, 580, 569]])

# Creating arrays with only Zeros

In [58]:
d = np.zeros((2,10),dtype = int)

In [59]:
d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [65]:
Zero = np.zeros((3,4),dtype = int)

In [66]:
Zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Creating an array with ones

In [67]:
Ones = np.ones((3,4),dtype = int)

In [68]:
Ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Creating a identity matrix

In [72]:
identity = np.identity(5, dtype = int)

In [73]:
identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Create an array filled with any specific number of specific dimensions.

In [82]:
full = np.full((3,5),6)

In [83]:
full

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [84]:
full.dtype

dtype('int64')

In [85]:
arr = np.full((2,7),3.14)

In [86]:
arr

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

# Array Concatenation

## create two arrays of same size

In [87]:
a1 = np.array([[1,2,3],[4,5,6]])

In [91]:
a2 = np.array([[7,8,9],[10,11,12]])

In [92]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
a2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [96]:
concat_array = np.concatenate([a1,a2],axis = 0)

## axis = 0 is row-wise concatenation

In [97]:
concat_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
concat_array = np.concatenate([a1,a2],axis = 1)

## axis = 1 is column-wise concatenation

In [99]:
concat_array

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Performing Mathematical operations on arrays

In [110]:
arr = np.array([1,2,3,4,5,6])

In [111]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [112]:
a = np.array([1,2,3])
b = np.array([2,2,2])

In [113]:
a * b

array([2, 4, 6])

a * b is element wise product.

## We can perform matrix multiplication using '@' symbol.

In [121]:
a1 = np.array([[1,1],[0,1]])
a2 = np.array([[2,0],[3,4]])

In [122]:
a1 @ a2

array([[5, 4],
       [3, 4]])

In [124]:
a1.dot(a2)

array([[5, 4],
       [3, 4]])

In [127]:
a = np.array([1,2,3])
b = np.array([2])

In [128]:
a * b

array([2, 4, 6])

In [139]:
a = np.random.random((2,3))

In [140]:
a 

array([[0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

## Adding row-wise

In [141]:
a.sum(axis = 0)

array([1.06294334, 1.16176934, 0.55801523])

## Adding column-wise

In [142]:
a.sum(axis = 1)

array([0.90154873, 1.88117918])

## Minimum element column-wise

In [143]:
a.min(axis = 1)

array([0.11827443, 0.41466194])

In [147]:
a = np.arange(10)**3

In [148]:
a[2 : 5]


array([ 8, 27, 64])

In [152]:
a[:6:2] = 1000
 # This is equivalent to a[0:6:2] = 1000

In [153]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [156]:
a = np.arange(24).reshape(2,3,4)

In [157]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [159]:
a[0][2][3]

11

In [ ]:
a[1][]